cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'

brew 'bash'
brew 'coreutils'
brew 'findutils'
brew 'ffmpeg'
brew 'git-flow'
brew 'gnupg'
brew 'gnupg2'
brew 'go'
brew 'grc'
brew 'httpie'
brew 'irssi'
brew 'mackup'
brew 'mongodb'
brew 'nvm'
brew 'opencc'
brew 'pyenv'
brew 'ssh-copy-id'
brew 'terraform'
brew 'trash'
brew 'tree'
brew 'unrar'
brew 'youtube-dl'

cask 'alfred'
cask 'atom'
cask 'beyond-compare'
cask 'firefoxdeveloperedition'
cask 'flux'
cask 'google-chrome'
cask 'istat-menus'
cask 'iterm2'
cask 'macdown'
cask 'ngrok'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'robomongo'
cask 'sketch'
cask 'sketch-toolbox'
cask 'sourcetree'

cask 'font-hack'
cask 'font-roboto'
cask 'font-source-code-pro'
